// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlncR2EG766xC3sweaRcr8zSN9HTCOQJU',
    appId: '1:1018739935570:web:baf718cf489b0fc000128b',
    messagingSenderId: '1018739935570',
    projectId: 'noor-islamic-app-911',
    authDomain: 'noor-islamic-app-911.firebaseapp.com',
    storageBucket: 'noor-islamic-app-911.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTI_YpwYcSmUXgbMyDng5c4UiYN23LZ3c',
    appId: '1:1018739935570:android:deca7f42fafccea400128b',
    messagingSenderId: '1018739935570',
    projectId: 'noor-islamic-app-911',
    storageBucket: 'noor-islamic-app-911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIdovFzAxQV6GmHCdawgCIB_qXSej7Pc',
    appId: '1:1018739935570:ios:ee395537ca4ad0d200128b',
    messagingSenderId: '1018739935570',
    projectId: 'noor-islamic-app-911',
    storageBucket: 'noor-islamic-app-911.firebasestorage.app',
    iosBundleId: 'com.example.muslimAppNew',
  );
}
