import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('ar'),
    Locale('en'),
    Locale('fr'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final instance =
        Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(instance != null, 'AppLocalizations was not found in widget tree.');
    return instance!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'appName': 'نور',
      'continue': 'متابعة',
      'startNow': 'ابدأ الآن',
      'onboardingTitle': 'نور - تطبيقك الإسلامي الشامل',
      'onboardingBody':
          'قرآن، أذكار، مواقيت صلاة، قبلة، ووضع Offline من أول تشغيل.',
      'quran': 'القرآن',
      'searchSurah': 'ابحث عن سورة',
      'noResults': 'لا توجد نتائج',
      'prayerTimes': 'مواقيت الصلاة',
      'azkar': 'الأذكار',
      'qibla': 'القبلة',
      'audio': 'التلاوات',
      'reciter': 'القارئ',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'textSize': 'حجم النص',
      'textSizeSmall': 'صغير',
      'textSizeLarge': 'كبير',
      'lineHeight': 'تباعد السطور',
      'lineHeightCompact': 'مضغوط',
      'lineHeightRelaxed': 'مريح',
      'highContrast': 'تباين عالٍ',
      'highContrastEnabled': 'مفعّل',
      'highContrastDisabled': 'غير مفعّل',
      'accessibilityPresets': 'إعدادات جاهزة للقراءة',
      'presetRecommended': 'موصى به',
      'presetBalanced': 'متوازن',
      'presetComfort': 'مريح للقراءة',
      'presetCompact': 'مضغوط',
      'resetAccessibility': 'إعادة ضبط الإتاحة',
      'tooltipTextSize': 'تكبير أو تصغير النصوص داخل التطبيق.',
      'tooltipLineHeight': 'زيادة المسافة بين السطور لقراءة أريح.',
      'tooltipHighContrast': 'تحسين وضوح الألوان لعناصر الواجهة.',
      'accessibilityGuide': 'دليل الإتاحة',
      'accessibilityGuideSubtitle': 'شرح سريع لضبط القراءة بما يناسبك.',
      'guideStepDisplayTitle': 'ابدأ بحجم النص',
      'guideStepDisplayBody':
          'استخدم شريط حجم النص للوصول إلى مستوى قراءة واضح ومريح لعينيك.',
      'guideStepReadabilityTitle': 'اضبط تباعد السطور',
      'guideStepReadabilityBody':
          'زيادة التباعد تجعل قراءة الفقرات الطويلة أسهل وتقلل إجهاد العين.',
      'guideStepContrastTitle': 'فعّل التباين عند الحاجة',
      'guideStepContrastBody':
          'إذا كانت الإضاءة قوية أو ضعيفة، جرّب التباين العالي لتحسين الوضوح.',
      'step': 'الخطوة',
      'previous': 'السابق',
      'done': 'تم',
      'applyRecommendedNow': 'تطبيق الإعداد الموصى به الآن',
      'dontShowGuideAgain': 'لا تظهر هذا الدليل مرة أخرى تلقائيًا',
      'preview': 'معاينة مباشرة',
      'previewBody':
          'بسم الله الرحمن الرحيم. هذا مثال يوضح شكل النص الحالي حسب إعداداتك.',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'تلقائي',
      'morning': 'الصباح',
      'evening': 'المساء',
      'morningEveningAzkar': 'أذكار الصباح والمساء',
      'counter': 'العداد',
      'resetCounter': 'تصفير العداد',
      'cancel': 'إلغاء',
      'nextPrayer': 'الصلاة القادمة',
      'noRemainingPrayer': 'لا توجد صلاة متبقية اليوم',
      'qiblaHint': 'ضع الهاتف على سطح مستوٍ لمعايرة اتجاه القبلة.',
      'qiblaAngle': 'زاوية القبلة',
      'qiblaSensorNotSupported': 'هذا الجهاز لا يدعم حساس البوصلة.',
      'openLocationSettings': 'فتح إعدادات الموقع',
      'qiblaAligned': 'الاتجاه مضبوط نحو القبلة',
      'qiblaAdjust': 'عدّل الاتجاه',
      'offlineReady': 'جاهز للعمل بدون إنترنت',
      'nowPlaying': 'قيد التشغيل',
      'audioError': 'تعذر تشغيل التلاوة. تحقق من اتصال الإنترنت.',
      'account': 'الحساب',
      'signedInAs': 'مسجل كـ',
      'anonymousUser': 'مستخدم ضيف',
      'signInGoogle': 'تسجيل عبر Google',
      'signInApple': 'تسجيل عبر Apple',
      'signInEmail': 'تسجيل بالبريد',
      'createAccountEmail': 'إنشاء حساب بالبريد',
      'signOut': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'bookmarkSaved': 'تم حفظ الإشارة المرجعية',
      'bookmarks': 'الإشارات المرجعية',
      'noBookmarks': 'لا توجد إشارات مرجعية بعد',
      'bookmarkDeleted': 'تم حذف الإشارة المرجعية',
      'surah': 'السورة',
      'ayah': 'الآية',
      'juz': 'الجزء',
      'page': 'الصفحة',
      'refreshQuran': 'تحديث بيانات القرآن',
      'quranRefreshed': 'تم تحديث قائمة السور',
      'readSurah': 'قراءة السورة',
      'quranHeroTitle': 'رحلة قرآنية يومية',
      'quranHeroSubtitle': 'ابدأ القراءة أو استكملها مع تجربة صوتية سلسة.',
      'openRecitations': 'فتح التلاوات',
      'timeRemaining': 'الوقت المتبقي',
      'azkarAvailable': 'الأذكار المتاحة',
      'dailyTasbeehGoal': 'هدف التسبيح اليومي',
      'remainingToGoal': 'المتبقي للهدف',
      'tapToCount': 'اضغط للعد',
      'compassLive': 'البوصلة المباشرة',
      'qiblaAlignmentExcellent': 'ممتاز',
      'qiblaAlignmentNeedsAdjust': 'يحتاج ضبط',
      'recalibrateQibla': 'إعادة معايرة القبلة',
      'readingProgress': 'تقدم القراءة',
      'jumpToAyah': 'الانتقال إلى آية',
      'quickTools': 'أدوات سريعة',
      'goToSelectedAyah': 'الانتقال للآية المحددة',
      'markAsLastRead': 'تم تحديث آخر قراءة',
      'downloadForOffline': 'تنزيل للاستخدام بدون إنترنت',
      'downloadedOffline': 'متاح بدون إنترنت',
      'downloadCompleted': 'اكتمل تنزيل السورة',
      'downloadFailed': 'فشل التنزيل، حاول مرة أخرى',
      'downloadFilteredSurahs': 'تنزيل السور الظاهرة',
      'clearReciterDownloads': 'حذف تنزيلات القارئ',
      'offlineFilesCount': 'عدد الملفات بدون إنترنت',
      'batchDownloadProgress': 'تقدم التنزيل الجماعي',
      'batchDownloadCompleted': 'اكتمل التنزيل الجماعي',
      'deletedOfflineFiles': 'تم حذف الملفات',
      'jumpToPage': 'الانتقال إلى صفحة',
      'goToSelectedPage': 'الانتقال للصفحة المحددة',
      'downloadFullMushaf': 'تنزيل المصحف كامل',
      'pauseBatchDownload': 'إيقاف التنزيل مؤقتًا',
      'resumeBatchDownload': 'استكمال التنزيل',
      'downloadsManagerTitle': 'إدارة التنزيلات',
      'storageUsed': 'المساحة المستخدمة',
      'noOfflineFiles': 'لا توجد ملفات أوفلاين لهذا القارئ',
      'deleteFile': 'حذف الملف',
    },
    'en': {
      'appName': 'Noor',
      'continue': 'Continue',
      'startNow': 'Start now',
      'onboardingTitle': 'Noor - Your Complete Islamic App',
      'onboardingBody':
          'Quran, Azkar, Prayer Times, Qibla, and offline support from day one.',
      'quran': 'Quran',
      'searchSurah': 'Search surah',
      'noResults': 'No results found',
      'prayerTimes': 'Prayer Times',
      'azkar': 'Azkar',
      'qibla': 'Qibla',
      'audio': 'Audio',
      'reciter': 'Reciter',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'textSize': 'Text size',
      'textSizeSmall': 'Small',
      'textSizeLarge': 'Large',
      'lineHeight': 'Line height',
      'lineHeightCompact': 'Compact',
      'lineHeightRelaxed': 'Relaxed',
      'highContrast': 'High contrast',
      'highContrastEnabled': 'Enabled',
      'highContrastDisabled': 'Disabled',
      'accessibilityPresets': 'Reading presets',
      'presetRecommended': 'Recommended',
      'presetBalanced': 'Balanced',
      'presetComfort': 'Comfort',
      'presetCompact': 'Compact',
      'resetAccessibility': 'Reset accessibility',
      'tooltipTextSize': 'Increase or decrease app text size.',
      'tooltipLineHeight': 'Adjust spacing between text lines for comfort.',
      'tooltipHighContrast': 'Boost color contrast for better readability.',
      'accessibilityGuide': 'Accessibility guide',
      'accessibilityGuideSubtitle':
          'A quick walkthrough to tune reading settings.',
      'guideStepDisplayTitle': 'Start with text size',
      'guideStepDisplayBody':
          'Use the text-size slider to reach a comfortable and clear reading level.',
      'guideStepReadabilityTitle': 'Adjust line height',
      'guideStepReadabilityBody':
          'More spacing between lines can make long passages easier to follow.',
      'guideStepContrastTitle': 'Use high contrast when needed',
      'guideStepContrastBody':
          'In bright or low light, high contrast can improve readability.',
      'step': 'Step',
      'previous': 'Previous',
      'done': 'Done',
      'applyRecommendedNow': 'Apply recommended now',
      'dontShowGuideAgain': 'Do not auto-show this guide again',
      'preview': 'Live preview',
      'previewBody':
          'In the name of Allah, the Most Merciful. This sample reflects your current reading settings.',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'morning': 'Morning',
      'evening': 'Evening',
      'morningEveningAzkar': 'Morning & Evening Azkar',
      'counter': 'Counter',
      'resetCounter': 'Reset counter',
      'cancel': 'Cancel',
      'nextPrayer': 'Next Prayer',
      'noRemainingPrayer': 'No remaining prayer today',
      'qiblaHint':
          'Place your phone on a flat surface to calibrate Qibla direction.',
      'qiblaAngle': 'Qibla angle',
      'qiblaSensorNotSupported':
          'This device does not support a compass sensor.',
      'openLocationSettings': 'Open location settings',
      'qiblaAligned': 'You are aligned with Qibla',
      'qiblaAdjust': 'Adjust direction',
      'offlineReady': 'Offline ready',
      'nowPlaying': 'Now playing',
      'audioError': 'Unable to play recitation. Check internet connection.',
      'account': 'Account',
      'signedInAs': 'Signed in as',
      'anonymousUser': 'Guest user',
      'signInGoogle': 'Sign in with Google',
      'signInApple': 'Sign in with Apple',
      'signInEmail': 'Sign in with Email',
      'createAccountEmail': 'Create account with Email',
      'signOut': 'Sign out',
      'email': 'Email',
      'password': 'Password',
      'bookmarkSaved': 'Bookmark saved',
      'bookmarks': 'Bookmarks',
      'noBookmarks': 'No bookmarks yet',
      'bookmarkDeleted': 'Bookmark deleted',
      'surah': 'Surah',
      'ayah': 'Ayah',
      'juz': 'Juz',
      'page': 'Page',
      'refreshQuran': 'Refresh Quran data',
      'quranRefreshed': 'Surahs list refreshed',
      'readSurah': 'Read surah',
      'quranHeroTitle': 'Your Daily Quran Journey',
      'quranHeroSubtitle':
          'Continue reading with focused visuals and smooth audio playback.',
      'openRecitations': 'Open recitations',
      'timeRemaining': 'Time remaining',
      'azkarAvailable': 'Azkar available',
      'dailyTasbeehGoal': 'Daily tasbeeh goal',
      'remainingToGoal': 'Remaining to goal',
      'tapToCount': 'Tap to count',
      'compassLive': 'Live compass',
      'qiblaAlignmentExcellent': 'Excellent',
      'qiblaAlignmentNeedsAdjust': 'Needs adjustment',
      'recalibrateQibla': 'Recalibrate qibla',
      'readingProgress': 'Reading progress',
      'jumpToAyah': 'Jump to ayah',
      'quickTools': 'Quick tools',
      'goToSelectedAyah': 'Go to selected ayah',
      'markAsLastRead': 'Last read updated',
      'downloadForOffline': 'Download for offline',
      'downloadedOffline': 'Available offline',
      'downloadCompleted': 'Surah download completed',
      'downloadFailed': 'Download failed, please try again',
      'downloadFilteredSurahs': 'Download visible surahs',
      'clearReciterDownloads': 'Clear reciter downloads',
      'offlineFilesCount': 'Offline files count',
      'batchDownloadProgress': 'Batch download progress',
      'batchDownloadCompleted': 'Batch download completed',
      'deletedOfflineFiles': 'Deleted files',
      'jumpToPage': 'Jump to page',
      'goToSelectedPage': 'Go to selected page',
      'downloadFullMushaf': 'Download full mushaf',
      'pauseBatchDownload': 'Pause download',
      'resumeBatchDownload': 'Resume download',
      'downloadsManagerTitle': 'Downloads manager',
      'storageUsed': 'Storage used',
      'noOfflineFiles': 'No offline files for this reciter',
      'deleteFile': 'Delete file',
    },
    'fr': {
      'appName': 'Noor',
      'continue': 'Continuer',
      'startNow': 'Commencer',
      'onboardingTitle': 'Noor - Votre application islamique complete',
      'onboardingBody':
          'Coran, Azkar, horaires de priere, Qibla et mode hors ligne des le premier lancement.',
      'quran': 'Coran',
      'searchSurah': 'Rechercher une sourate',
      'noResults': 'Aucun resultat',
      'prayerTimes': 'Horaires de priere',
      'azkar': 'Azkar',
      'qibla': 'Qibla',
      'audio': 'Recitations',
      'reciter': 'Recitateur',
      'settings': 'Parametres',
      'language': 'Langue',
      'theme': 'Theme',
      'textSize': 'Taille du texte',
      'textSizeSmall': 'Petit',
      'textSizeLarge': 'Grand',
      'lineHeight': 'Interligne',
      'lineHeightCompact': 'Compact',
      'lineHeightRelaxed': 'Aere',
      'highContrast': 'Contraste eleve',
      'highContrastEnabled': 'Active',
      'highContrastDisabled': 'Desactive',
      'accessibilityPresets': 'Profils de lecture',
      'presetRecommended': 'Recommande',
      'presetBalanced': 'Equilibre',
      'presetComfort': 'Confort',
      'presetCompact': 'Compact',
      'resetAccessibility': 'Reinitialiser l acces',
      'tooltipTextSize':
          'Augmenter ou reduire la taille du texte dans l application.',
      'tooltipLineHeight':
          'Ajuster l espace entre les lignes pour une lecture confortable.',
      'tooltipHighContrast':
          'Renforcer le contraste des couleurs pour une meilleure lisibilite.',
      'accessibilityGuide': 'Guide d accessibilite',
      'accessibilityGuideSubtitle':
          'Une aide rapide pour ajuster votre lecture.',
      'guideStepDisplayTitle': 'Commencez par la taille du texte',
      'guideStepDisplayBody':
          'Utilisez le curseur de taille pour obtenir une lecture claire et confortable.',
      'guideStepReadabilityTitle': 'Ajustez l interligne',
      'guideStepReadabilityBody':
          'Un interligne plus grand facilite la lecture des passages longs.',
      'guideStepContrastTitle': 'Activez le contraste eleve si besoin',
      'guideStepContrastBody':
          'En lumiere forte ou faible, le contraste eleve peut ameliorer la lisibilite.',
      'step': 'Etape',
      'previous': 'Precedent',
      'done': 'Termine',
      'applyRecommendedNow': 'Appliquer le profil recommande',
      'dontShowGuideAgain': 'Ne plus afficher automatiquement ce guide',
      'preview': 'Apercu en direct',
      'previewBody':
          'Au nom d Allah, le Tout Misericordieux. Cet exemple montre vos reglages de lecture actuels.',
      'light': 'Clair',
      'dark': 'Sombre',
      'system': 'Systeme',
      'morning': 'Matin',
      'evening': 'Soir',
      'morningEveningAzkar': 'Azkar du matin et du soir',
      'counter': 'Compteur',
      'resetCounter': 'Reinitialiser le compteur',
      'cancel': 'Annuler',
      'nextPrayer': 'Prochaine priere',
      'noRemainingPrayer': 'Aucune priere restante aujourd\'hui',
      'qiblaHint':
          'Posez le telephone sur une surface plane pour calibrer la direction Qibla.',
      'qiblaAngle': 'Angle de la Qibla',
      'qiblaSensorNotSupported':
          'Cet appareil ne prend pas en charge le capteur de boussole.',
      'openLocationSettings': 'Ouvrir les parametres de localisation',
      'qiblaAligned': 'Vous etes aligne vers la Qibla',
      'qiblaAdjust': 'Ajustez la direction',
      'offlineReady': 'Pret hors ligne',
      'nowPlaying': 'Lecture en cours',
      'audioError':
          'Impossible de lire la recitation. Verifiez la connexion internet.',
      'account': 'Compte',
      'signedInAs': 'Connecte en tant que',
      'anonymousUser': 'Utilisateur invite',
      'signInGoogle': 'Connexion avec Google',
      'signInApple': 'Connexion avec Apple',
      'signInEmail': 'Connexion avec email',
      'createAccountEmail': 'Creer un compte par email',
      'signOut': 'Se deconnecter',
      'email': 'Email',
      'password': 'Mot de passe',
      'bookmarkSaved': 'Signet enregistre',
      'bookmarks': 'Signets',
      'noBookmarks': 'Aucun signet pour le moment',
      'bookmarkDeleted': 'Signet supprime',
      'surah': 'Sourate',
      'ayah': 'Verset',
      'juz': 'Juz',
      'page': 'Page',
      'refreshQuran': 'Actualiser les donnees du Coran',
      'quranRefreshed': 'Liste des sourates mise a jour',
      'readSurah': 'Lire la sourate',
      'quranHeroTitle': 'Votre parcours coranique quotidien',
      'quranHeroSubtitle':
          'Reprenez la lecture avec une interface claire et une ecoute fluide.',
      'openRecitations': 'Ouvrir les recitations',
      'timeRemaining': 'Temps restant',
      'azkarAvailable': 'Azkar disponibles',
      'dailyTasbeehGoal': 'Objectif quotidien de tasbeeh',
      'remainingToGoal': 'Restant pour l objectif',
      'tapToCount': 'Touchez pour compter',
      'compassLive': 'Boussole en direct',
      'qiblaAlignmentExcellent': 'Excellent',
      'qiblaAlignmentNeedsAdjust': 'A ajuster',
      'recalibrateQibla': 'Recalibrer la qibla',
      'readingProgress': 'Progression de lecture',
      'jumpToAyah': 'Aller au verset',
      'quickTools': 'Outils rapides',
      'goToSelectedAyah': 'Aller au verset selectionne',
      'markAsLastRead': 'Derniere lecture mise a jour',
      'downloadForOffline': 'Telecharger pour hors ligne',
      'downloadedOffline': 'Disponible hors ligne',
      'downloadCompleted': 'Telechargement de la sourate termine',
      'downloadFailed': 'Echec du telechargement, reessayez',
      'downloadFilteredSurahs': 'Telecharger les sourates affichees',
      'clearReciterDownloads': 'Effacer les telechargements du recitateur',
      'offlineFilesCount': 'Nombre de fichiers hors ligne',
      'batchDownloadProgress': 'Progression du telechargement groupe',
      'batchDownloadCompleted': 'Telechargement groupe termine',
      'deletedOfflineFiles': 'Fichiers supprimes',
      'jumpToPage': 'Aller a la page',
      'goToSelectedPage': 'Aller a la page selectionnee',
      'downloadFullMushaf': 'Telecharger le mushaf complet',
      'pauseBatchDownload': 'Mettre le telechargement en pause',
      'resumeBatchDownload': 'Reprendre le telechargement',
      'downloadsManagerTitle': 'Gestion des telechargements',
      'storageUsed': 'Espace utilise',
      'noOfflineFiles': 'Aucun fichier hors ligne pour ce recitateur',
      'deleteFile': 'Supprimer le fichier',
    },
  };

  String tr(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
        (supported) => supported.languageCode == locale.languageCode,
      );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension LocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
